title: Mathilde ter Veen
logo: /assets/img/logo.png
description: Data Scientist - Project Manager
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: tuur29/pages-themes-cayman
