title: Mathilde ter Veen
description: Data Scientist - Project Manager
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://www.linkedin.com/in/mathildeterveen
  zip_title: LinkedIn
  zip_hide: false
  tar_hide: true
  github_hide: true
